main:
  host: 0.0.0.0
  port: 9090

log:
  level: debug        # panic, fatal, error, warn, info, debug, trace
  out: stdout         # stdout or [filepath]

gin:
  mode: debug         # debug, release, test

mysql:
  user: root
  passwd: mypassword
  host: 120.25.0.102
  port: 3306
  db_name: douyin_12306

redis:
  addr: 120.25.0.102:6379
  username:
  password: root
  db: 0

