services:
  api:
    name: api
    addr: 0.0.0.0:9090
    mode: debug   # debug, release, test
    timeout: 5    # 单位: s
  user:
    name: user
    addr: 0.0.0.0:9091
    client:
      mux_connection: 1
      rpc_timeout: 3    # 单位: s
      conn_timeout: 50  # 单位: ms
    server:
      max_connections: 1000
      max_qps: 100
  video:
    name: video
    addr: 0.0.0.0:9092
    client:
      mux_connection: 1
      rpc_timeout: 3    # 单位: s
      conn_timeout: 50  # 单位: ms
    server:
      max_connections: 1000
      max_qps: 100

etcd:
  address: 0.0.0.0:2379

log:
  level: debug  # panic, fatal, error, warn, info, debug, trace
  out: stdout   # stdout, [filepath]

mysql:
  user: root
  passwd: mypassword
  host: 120.25.0.102
  port: 3306
  db_name: douyin_12306
  log:
    level: info                           # info, warn, error, silent
    out: stdout                           # stdout, [filepath]
    slow_threshold: 500                   # 单位: ms
    ignore_record_not_found_error: false  # true, false

redis:
  addr: 120.25.0.102:6379
  username:
  password: root
  db: 0
