version: '3'

services:
  etcd:
    image: 'bitnami/etcd:latest'
    platform: linux/x86_64
    ports:
      - "2379:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes

  jaeger:
    image: jaegertracing/all-in-one:latest
    platform: linux/x86_64
    ports:
      - "6831:6831/udp"
      - "16686:16686"
