version: '3'

volumes:
  mysql_volume:

services:
  mysql-service:
    build: ./repository/mysqlDB
    platform: linux/x86_64
    volumes:
      - type: volume
        source: mysql_volume
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: r1o2o3t
      MYSQL_USER: douyin_12306
      MYSQL_PASSWORD: d1o2u3y0i6n
      MYSQL_DATABASE: douyin_12306
    restart: always

  main-service:
    build: .
    platform: linux/x86_64
    environment:
      MYSQL_USER: douyin_12306
      MYSQL_PASSWD: d1o2u3y0i6n
      MYSQL_HOST: mysql-service
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: douyin_12306
    depends_on:
      - mysql-service
    ports:
      - "9090:9090" # [本机端口:容器端口]
    restart: always
