// Code generated by Kitex v0.3.1. DO NOT EDIT.

package videoservice

import (
	"context"
	"douyin-12306/kitex_gen/videoKitex"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Feed(ctx context.Context, Req *videoKitex.FeedRequest, callOptions ...callopt.Option) (r *videoKitex.FeedResponse, err error)
	PublishAction(ctx context.Context, Req *videoKitex.PublishActionRequest, callOptions ...callopt.Option) (r *videoKitex.PublishActionResponse, err error)
	QueryPublishList(ctx context.Context, Req *videoKitex.PublishListRequest, callOptions ...callopt.Option) (r *videoKitex.PublishListResponse, err error)
	FavoriteAction(ctx context.Context, Req *videoKitex.FavoriteActionRequest, callOptions ...callopt.Option) (r *videoKitex.FavoriteActionResponse, err error)
	QueryFavoriteList(ctx context.Context, Req *videoKitex.FavoriteListRequest, callOptions ...callopt.Option) (r *videoKitex.FavoriteListResponse, err error)
	CommentAction(ctx context.Context, Req *videoKitex.CommentActionRequest, callOptions ...callopt.Option) (r *videoKitex.CommentActionResponse, err error)
	QueryCommentList(ctx context.Context, Req *videoKitex.CommentListRequset, callOptions ...callopt.Option) (r *videoKitex.CommentListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoServiceClient struct {
	*kClient
}

func (p *kVideoServiceClient) Feed(ctx context.Context, Req *videoKitex.FeedRequest, callOptions ...callopt.Option) (r *videoKitex.FeedResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Feed(ctx, Req)
}

func (p *kVideoServiceClient) PublishAction(ctx context.Context, Req *videoKitex.PublishActionRequest, callOptions ...callopt.Option) (r *videoKitex.PublishActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishAction(ctx, Req)
}

func (p *kVideoServiceClient) QueryPublishList(ctx context.Context, Req *videoKitex.PublishListRequest, callOptions ...callopt.Option) (r *videoKitex.PublishListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryPublishList(ctx, Req)
}

func (p *kVideoServiceClient) FavoriteAction(ctx context.Context, Req *videoKitex.FavoriteActionRequest, callOptions ...callopt.Option) (r *videoKitex.FavoriteActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FavoriteAction(ctx, Req)
}

func (p *kVideoServiceClient) QueryFavoriteList(ctx context.Context, Req *videoKitex.FavoriteListRequest, callOptions ...callopt.Option) (r *videoKitex.FavoriteListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryFavoriteList(ctx, Req)
}

func (p *kVideoServiceClient) CommentAction(ctx context.Context, Req *videoKitex.CommentActionRequest, callOptions ...callopt.Option) (r *videoKitex.CommentActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentAction(ctx, Req)
}

func (p *kVideoServiceClient) QueryCommentList(ctx context.Context, Req *videoKitex.CommentListRequset, callOptions ...callopt.Option) (r *videoKitex.CommentListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryCommentList(ctx, Req)
}
