// Code generated by Kitex v0.3.1. DO NOT EDIT.

package userservice

import (
	"context"
	"douyin-12306/kitex_gen/userKitex"
	"fmt"
	"github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	"github.com/cloudwego/kitex/pkg/streaming"
	"google.golang.org/protobuf/proto"
)

func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

var userServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*userKitex.UserService)(nil)
	methods := map[string]kitex.MethodInfo{
		"RegisterUser":      kitex.NewMethodInfo(registerUserHandler, newRegisterUserArgs, newRegisterUserResult, false),
		"LoginUser":         kitex.NewMethodInfo(loginUserHandler, newLoginUserArgs, newLoginUserResult, false),
		"QueryUserInfo":     kitex.NewMethodInfo(queryUserInfoHandler, newQueryUserInfoArgs, newQueryUserInfoResult, false),
		"RelationAction":    kitex.NewMethodInfo(relationActionHandler, newRelationActionArgs, newRelationActionResult, false),
		"QueryFollowList":   kitex.NewMethodInfo(queryFollowListHandler, newQueryFollowListArgs, newQueryFollowListResult, false),
		"QueryFollowerList": kitex.NewMethodInfo(queryFollowerListHandler, newQueryFollowerListArgs, newQueryFollowerListResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.3.1",
		Extra:           extra,
	}
	return svcInfo
}

func registerUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(userKitex.UserRegisterRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(userKitex.UserService).RegisterUser(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *RegisterUserArgs:
		success, err := handler.(userKitex.UserService).RegisterUser(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RegisterUserResult)
		realResult.Success = success
	}
	return nil
}
func newRegisterUserArgs() interface{} {
	return &RegisterUserArgs{}
}

func newRegisterUserResult() interface{} {
	return &RegisterUserResult{}
}

type RegisterUserArgs struct {
	Req *userKitex.UserRegisterRequest
}

func (p *RegisterUserArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in RegisterUserArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *RegisterUserArgs) Unmarshal(in []byte) error {
	msg := new(userKitex.UserRegisterRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RegisterUserArgs_Req_DEFAULT *userKitex.UserRegisterRequest

func (p *RegisterUserArgs) GetReq() *userKitex.UserRegisterRequest {
	if !p.IsSetReq() {
		return RegisterUserArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RegisterUserArgs) IsSetReq() bool {
	return p.Req != nil
}

type RegisterUserResult struct {
	Success *userKitex.UserRegisterResponse
}

var RegisterUserResult_Success_DEFAULT *userKitex.UserRegisterResponse

func (p *RegisterUserResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in RegisterUserResult")
	}
	return proto.Marshal(p.Success)
}

func (p *RegisterUserResult) Unmarshal(in []byte) error {
	msg := new(userKitex.UserRegisterResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RegisterUserResult) GetSuccess() *userKitex.UserRegisterResponse {
	if !p.IsSetSuccess() {
		return RegisterUserResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RegisterUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*userKitex.UserRegisterResponse)
}

func (p *RegisterUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func loginUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(userKitex.UserLoginRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(userKitex.UserService).LoginUser(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *LoginUserArgs:
		success, err := handler.(userKitex.UserService).LoginUser(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*LoginUserResult)
		realResult.Success = success
	}
	return nil
}
func newLoginUserArgs() interface{} {
	return &LoginUserArgs{}
}

func newLoginUserResult() interface{} {
	return &LoginUserResult{}
}

type LoginUserArgs struct {
	Req *userKitex.UserLoginRequest
}

func (p *LoginUserArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in LoginUserArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *LoginUserArgs) Unmarshal(in []byte) error {
	msg := new(userKitex.UserLoginRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var LoginUserArgs_Req_DEFAULT *userKitex.UserLoginRequest

func (p *LoginUserArgs) GetReq() *userKitex.UserLoginRequest {
	if !p.IsSetReq() {
		return LoginUserArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *LoginUserArgs) IsSetReq() bool {
	return p.Req != nil
}

type LoginUserResult struct {
	Success *userKitex.UserLoginResponse
}

var LoginUserResult_Success_DEFAULT *userKitex.UserLoginResponse

func (p *LoginUserResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in LoginUserResult")
	}
	return proto.Marshal(p.Success)
}

func (p *LoginUserResult) Unmarshal(in []byte) error {
	msg := new(userKitex.UserLoginResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *LoginUserResult) GetSuccess() *userKitex.UserLoginResponse {
	if !p.IsSetSuccess() {
		return LoginUserResult_Success_DEFAULT
	}
	return p.Success
}

func (p *LoginUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*userKitex.UserLoginResponse)
}

func (p *LoginUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func queryUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(userKitex.UserInfoRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(userKitex.UserService).QueryUserInfo(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *QueryUserInfoArgs:
		success, err := handler.(userKitex.UserService).QueryUserInfo(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*QueryUserInfoResult)
		realResult.Success = success
	}
	return nil
}
func newQueryUserInfoArgs() interface{} {
	return &QueryUserInfoArgs{}
}

func newQueryUserInfoResult() interface{} {
	return &QueryUserInfoResult{}
}

type QueryUserInfoArgs struct {
	Req *userKitex.UserInfoRequest
}

func (p *QueryUserInfoArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in QueryUserInfoArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *QueryUserInfoArgs) Unmarshal(in []byte) error {
	msg := new(userKitex.UserInfoRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var QueryUserInfoArgs_Req_DEFAULT *userKitex.UserInfoRequest

func (p *QueryUserInfoArgs) GetReq() *userKitex.UserInfoRequest {
	if !p.IsSetReq() {
		return QueryUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *QueryUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

type QueryUserInfoResult struct {
	Success *userKitex.UserInfoResponse
}

var QueryUserInfoResult_Success_DEFAULT *userKitex.UserInfoResponse

func (p *QueryUserInfoResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in QueryUserInfoResult")
	}
	return proto.Marshal(p.Success)
}

func (p *QueryUserInfoResult) Unmarshal(in []byte) error {
	msg := new(userKitex.UserInfoResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *QueryUserInfoResult) GetSuccess() *userKitex.UserInfoResponse {
	if !p.IsSetSuccess() {
		return QueryUserInfoResult_Success_DEFAULT
	}
	return p.Success
}

func (p *QueryUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*userKitex.UserInfoResponse)
}

func (p *QueryUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func relationActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(userKitex.RelationActionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(userKitex.UserService).RelationAction(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *RelationActionArgs:
		success, err := handler.(userKitex.UserService).RelationAction(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RelationActionResult)
		realResult.Success = success
	}
	return nil
}
func newRelationActionArgs() interface{} {
	return &RelationActionArgs{}
}

func newRelationActionResult() interface{} {
	return &RelationActionResult{}
}

type RelationActionArgs struct {
	Req *userKitex.RelationActionRequest
}

func (p *RelationActionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in RelationActionArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *RelationActionArgs) Unmarshal(in []byte) error {
	msg := new(userKitex.RelationActionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RelationActionArgs_Req_DEFAULT *userKitex.RelationActionRequest

func (p *RelationActionArgs) GetReq() *userKitex.RelationActionRequest {
	if !p.IsSetReq() {
		return RelationActionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RelationActionArgs) IsSetReq() bool {
	return p.Req != nil
}

type RelationActionResult struct {
	Success *userKitex.RelationActionResponse
}

var RelationActionResult_Success_DEFAULT *userKitex.RelationActionResponse

func (p *RelationActionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in RelationActionResult")
	}
	return proto.Marshal(p.Success)
}

func (p *RelationActionResult) Unmarshal(in []byte) error {
	msg := new(userKitex.RelationActionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RelationActionResult) GetSuccess() *userKitex.RelationActionResponse {
	if !p.IsSetSuccess() {
		return RelationActionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RelationActionResult) SetSuccess(x interface{}) {
	p.Success = x.(*userKitex.RelationActionResponse)
}

func (p *RelationActionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func queryFollowListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(userKitex.FollowListRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(userKitex.UserService).QueryFollowList(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *QueryFollowListArgs:
		success, err := handler.(userKitex.UserService).QueryFollowList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*QueryFollowListResult)
		realResult.Success = success
	}
	return nil
}
func newQueryFollowListArgs() interface{} {
	return &QueryFollowListArgs{}
}

func newQueryFollowListResult() interface{} {
	return &QueryFollowListResult{}
}

type QueryFollowListArgs struct {
	Req *userKitex.FollowListRequest
}

func (p *QueryFollowListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in QueryFollowListArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *QueryFollowListArgs) Unmarshal(in []byte) error {
	msg := new(userKitex.FollowListRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var QueryFollowListArgs_Req_DEFAULT *userKitex.FollowListRequest

func (p *QueryFollowListArgs) GetReq() *userKitex.FollowListRequest {
	if !p.IsSetReq() {
		return QueryFollowListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *QueryFollowListArgs) IsSetReq() bool {
	return p.Req != nil
}

type QueryFollowListResult struct {
	Success *userKitex.FollowListResponse
}

var QueryFollowListResult_Success_DEFAULT *userKitex.FollowListResponse

func (p *QueryFollowListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in QueryFollowListResult")
	}
	return proto.Marshal(p.Success)
}

func (p *QueryFollowListResult) Unmarshal(in []byte) error {
	msg := new(userKitex.FollowListResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *QueryFollowListResult) GetSuccess() *userKitex.FollowListResponse {
	if !p.IsSetSuccess() {
		return QueryFollowListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *QueryFollowListResult) SetSuccess(x interface{}) {
	p.Success = x.(*userKitex.FollowListResponse)
}

func (p *QueryFollowListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func queryFollowerListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(userKitex.FollowerListRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(userKitex.UserService).QueryFollowerList(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *QueryFollowerListArgs:
		success, err := handler.(userKitex.UserService).QueryFollowerList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*QueryFollowerListResult)
		realResult.Success = success
	}
	return nil
}
func newQueryFollowerListArgs() interface{} {
	return &QueryFollowerListArgs{}
}

func newQueryFollowerListResult() interface{} {
	return &QueryFollowerListResult{}
}

type QueryFollowerListArgs struct {
	Req *userKitex.FollowerListRequest
}

func (p *QueryFollowerListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in QueryFollowerListArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *QueryFollowerListArgs) Unmarshal(in []byte) error {
	msg := new(userKitex.FollowerListRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var QueryFollowerListArgs_Req_DEFAULT *userKitex.FollowerListRequest

func (p *QueryFollowerListArgs) GetReq() *userKitex.FollowerListRequest {
	if !p.IsSetReq() {
		return QueryFollowerListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *QueryFollowerListArgs) IsSetReq() bool {
	return p.Req != nil
}

type QueryFollowerListResult struct {
	Success *userKitex.FollowerListResponse
}

var QueryFollowerListResult_Success_DEFAULT *userKitex.FollowerListResponse

func (p *QueryFollowerListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in QueryFollowerListResult")
	}
	return proto.Marshal(p.Success)
}

func (p *QueryFollowerListResult) Unmarshal(in []byte) error {
	msg := new(userKitex.FollowerListResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *QueryFollowerListResult) GetSuccess() *userKitex.FollowerListResponse {
	if !p.IsSetSuccess() {
		return QueryFollowerListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *QueryFollowerListResult) SetSuccess(x interface{}) {
	p.Success = x.(*userKitex.FollowerListResponse)
}

func (p *QueryFollowerListResult) IsSetSuccess() bool {
	return p.Success != nil
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) RegisterUser(ctx context.Context, Req *userKitex.UserRegisterRequest) (r *userKitex.UserRegisterResponse, err error) {
	var _args RegisterUserArgs
	_args.Req = Req
	var _result RegisterUserResult
	if err = p.c.Call(ctx, "RegisterUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LoginUser(ctx context.Context, Req *userKitex.UserLoginRequest) (r *userKitex.UserLoginResponse, err error) {
	var _args LoginUserArgs
	_args.Req = Req
	var _result LoginUserResult
	if err = p.c.Call(ctx, "LoginUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryUserInfo(ctx context.Context, Req *userKitex.UserInfoRequest) (r *userKitex.UserInfoResponse, err error) {
	var _args QueryUserInfoArgs
	_args.Req = Req
	var _result QueryUserInfoResult
	if err = p.c.Call(ctx, "QueryUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RelationAction(ctx context.Context, Req *userKitex.RelationActionRequest) (r *userKitex.RelationActionResponse, err error) {
	var _args RelationActionArgs
	_args.Req = Req
	var _result RelationActionResult
	if err = p.c.Call(ctx, "RelationAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryFollowList(ctx context.Context, Req *userKitex.FollowListRequest) (r *userKitex.FollowListResponse, err error) {
	var _args QueryFollowListArgs
	_args.Req = Req
	var _result QueryFollowListResult
	if err = p.c.Call(ctx, "QueryFollowList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryFollowerList(ctx context.Context, Req *userKitex.FollowerListRequest) (r *userKitex.FollowerListResponse, err error) {
	var _args QueryFollowerListArgs
	_args.Req = Req
	var _result QueryFollowerListResult
	if err = p.c.Call(ctx, "QueryFollowerList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
