// Code generated by Kitex v0.3.1. DO NOT EDIT.

package userservice

import (
	"context"
	"douyin-12306/kitex_gen/userKitex"
	"fmt"
	"github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	"github.com/cloudwego/kitex/pkg/streaming"
	"google.golang.org/protobuf/proto"
)

func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

var userServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*userKitex.UserService)(nil)
	methods := map[string]kitex.MethodInfo{
		"RegisterUser":  kitex.NewMethodInfo(registerUserHandler, newRegisterUserArgs, newRegisterUserResult, false),
		"LoginUser":     kitex.NewMethodInfo(loginUserHandler, newLoginUserArgs, newLoginUserResult, false),
		"QueryUserInfo": kitex.NewMethodInfo(queryUserInfoHandler, newQueryUserInfoArgs, newQueryUserInfoResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.3.1",
		Extra:           extra,
	}
	return svcInfo
}

func registerUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(userKitex.UserRegisterRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(userKitex.UserService).RegisterUser(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *RegisterUserArgs:
		success, err := handler.(userKitex.UserService).RegisterUser(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RegisterUserResult)
		realResult.Success = success
	}
	return nil
}
func newRegisterUserArgs() interface{} {
	return &RegisterUserArgs{}
}

func newRegisterUserResult() interface{} {
	return &RegisterUserResult{}
}

type RegisterUserArgs struct {
	Req *userKitex.UserRegisterRequest
}

func (p *RegisterUserArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in RegisterUserArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *RegisterUserArgs) Unmarshal(in []byte) error {
	msg := new(userKitex.UserRegisterRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RegisterUserArgs_Req_DEFAULT *userKitex.UserRegisterRequest

func (p *RegisterUserArgs) GetReq() *userKitex.UserRegisterRequest {
	if !p.IsSetReq() {
		return RegisterUserArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RegisterUserArgs) IsSetReq() bool {
	return p.Req != nil
}

type RegisterUserResult struct {
	Success *userKitex.UserRegisterResponse
}

var RegisterUserResult_Success_DEFAULT *userKitex.UserRegisterResponse

func (p *RegisterUserResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in RegisterUserResult")
	}
	return proto.Marshal(p.Success)
}

func (p *RegisterUserResult) Unmarshal(in []byte) error {
	msg := new(userKitex.UserRegisterResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RegisterUserResult) GetSuccess() *userKitex.UserRegisterResponse {
	if !p.IsSetSuccess() {
		return RegisterUserResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RegisterUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*userKitex.UserRegisterResponse)
}

func (p *RegisterUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func loginUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(userKitex.UserLoginRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(userKitex.UserService).LoginUser(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *LoginUserArgs:
		success, err := handler.(userKitex.UserService).LoginUser(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*LoginUserResult)
		realResult.Success = success
	}
	return nil
}
func newLoginUserArgs() interface{} {
	return &LoginUserArgs{}
}

func newLoginUserResult() interface{} {
	return &LoginUserResult{}
}

type LoginUserArgs struct {
	Req *userKitex.UserLoginRequest
}

func (p *LoginUserArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in LoginUserArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *LoginUserArgs) Unmarshal(in []byte) error {
	msg := new(userKitex.UserLoginRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var LoginUserArgs_Req_DEFAULT *userKitex.UserLoginRequest

func (p *LoginUserArgs) GetReq() *userKitex.UserLoginRequest {
	if !p.IsSetReq() {
		return LoginUserArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *LoginUserArgs) IsSetReq() bool {
	return p.Req != nil
}

type LoginUserResult struct {
	Success *userKitex.UserLoginResponse
}

var LoginUserResult_Success_DEFAULT *userKitex.UserLoginResponse

func (p *LoginUserResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in LoginUserResult")
	}
	return proto.Marshal(p.Success)
}

func (p *LoginUserResult) Unmarshal(in []byte) error {
	msg := new(userKitex.UserLoginResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *LoginUserResult) GetSuccess() *userKitex.UserLoginResponse {
	if !p.IsSetSuccess() {
		return LoginUserResult_Success_DEFAULT
	}
	return p.Success
}

func (p *LoginUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*userKitex.UserLoginResponse)
}

func (p *LoginUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func queryUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(userKitex.UserInfoRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(userKitex.UserService).QueryUserInfo(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *QueryUserInfoArgs:
		success, err := handler.(userKitex.UserService).QueryUserInfo(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*QueryUserInfoResult)
		realResult.Success = success
	}
	return nil
}
func newQueryUserInfoArgs() interface{} {
	return &QueryUserInfoArgs{}
}

func newQueryUserInfoResult() interface{} {
	return &QueryUserInfoResult{}
}

type QueryUserInfoArgs struct {
	Req *userKitex.UserInfoRequest
}

func (p *QueryUserInfoArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in QueryUserInfoArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *QueryUserInfoArgs) Unmarshal(in []byte) error {
	msg := new(userKitex.UserInfoRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var QueryUserInfoArgs_Req_DEFAULT *userKitex.UserInfoRequest

func (p *QueryUserInfoArgs) GetReq() *userKitex.UserInfoRequest {
	if !p.IsSetReq() {
		return QueryUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *QueryUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

type QueryUserInfoResult struct {
	Success *userKitex.UserInfoResponse
}

var QueryUserInfoResult_Success_DEFAULT *userKitex.UserInfoResponse

func (p *QueryUserInfoResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in QueryUserInfoResult")
	}
	return proto.Marshal(p.Success)
}

func (p *QueryUserInfoResult) Unmarshal(in []byte) error {
	msg := new(userKitex.UserInfoResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *QueryUserInfoResult) GetSuccess() *userKitex.UserInfoResponse {
	if !p.IsSetSuccess() {
		return QueryUserInfoResult_Success_DEFAULT
	}
	return p.Success
}

func (p *QueryUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*userKitex.UserInfoResponse)
}

func (p *QueryUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) RegisterUser(ctx context.Context, Req *userKitex.UserRegisterRequest) (r *userKitex.UserRegisterResponse, err error) {
	var _args RegisterUserArgs
	_args.Req = Req
	var _result RegisterUserResult
	if err = p.c.Call(ctx, "RegisterUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LoginUser(ctx context.Context, Req *userKitex.UserLoginRequest) (r *userKitex.UserLoginResponse, err error) {
	var _args LoginUserArgs
	_args.Req = Req
	var _result LoginUserResult
	if err = p.c.Call(ctx, "LoginUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryUserInfo(ctx context.Context, Req *userKitex.UserInfoRequest) (r *userKitex.UserInfoResponse, err error) {
	var _args QueryUserInfoArgs
	_args.Req = Req
	var _result QueryUserInfoResult
	if err = p.c.Call(ctx, "QueryUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
